### PR TITLE
#12 Created new case 'TVSA2' where vacuum pressure is reached

### PR DESCRIPTION
**Pull request by vajcsi**
Created the TVSA2 cycle that works properly. I think it's best to work off of that and remove the original one. The new one has only 3 components at the moment, but I don't see that being the issue. 

"3_source/4_rhs/1_volumetricFlowRates/3_auxiliary_units/calcVolFlows4UnitsFlowCtrlDT1AccExTa.m" was missing a parameter unpack.

colPresProfile

### CODE REVIEW

**Comment by taehunk333** [comment]
@vajcsi, did you merge this branch into develop yourself? We cannot merge our own merge requests to develop and have each other merge our requests into develop; this is the best practice with collaboration on a project...

Could you please explain what you are trying to do so that we can properly merge the branch int develop?

Thanks!

**Comment by taehunk333** [comment]
Also, let's add proper labels and select TVSA as the project! ;)

**Comment by vajcsi** [comment]
Hi @taehunk333 ,

Here’s what I’ve been working on:
1. The file calcVolFlows4UnitsFlowCtrlDT1AccExTa.m was missing a variable from the params struct, so I unpacked it to ensure it can be used correctly.
2. The t2purge case, a 3-step cycle designed for testing the desorption and purge steps of the TVSA cycle, reached vacuum pressure with the appropriate Cv values. However, I couldn’t replicate this behavior in the TVSA case. To address this, I created a new cycle called TVSA2, which mirrors the TVSA cycle but maintains vacuum pressure throughout steps 2-6. If needed, we can delete the original TVSA cycle, but for now, I’m just not using it.

I’m trying to follow the workflow guidelines as closely as possible, but my working methods might not fit very well. If I understand correctly, branches of branches shouldn’t be created, and merging my own work should be avoided. Is there a way to continue building on improvements while keeping issues/tickets separate?

**Comment by taehunk333** [comment]
> Hi @taehunk333 ,
> 
> Here’s what I’ve been working on:
> 
> 1. The file calcVolFlows4UnitsFlowCtrlDT1AccExTa.m was missing a variable from the params struct, so I unpacked it to ensure it can be used correctly.
> 2. The t2purge case, a 3-step cycle designed for testing the desorption and purge steps of the TVSA cycle, reached vacuum pressure with the appropriate Cv values. However, I couldn’t replicate this behavior in the TVSA case. To address this, I created a new cycle called TVSA2, which mirrors the TVSA cycle but maintains vacuum pressure throughout steps 2-6. If needed, we can delete the original TVSA cycle, but for now, I’m just not using it.
> 
> I’m trying to follow the workflow guidelines as closely as possible, but my working methods might not fit very well. If I understand correctly, branches of branches shouldn’t be created, and merging my own work should be avoided. Is there a way to continue building on improvements while keeping issues/tickets separate?

Thanks @vajcsi for the update and thanks for your patience! We are all learning to work with GitHub, and I promise that we will figure out good ways that would allow us to be productive, while maintaining the best code quality. 

Yes, in terms of the main points, those two you mentioned are the main points. 

To be honest with you, I also struggled with this first, but the most important thing we can do to make our lives easy as developers is to create a ticket with a well-defined scope. Sometimes we create tickets that are too huge in scope, and it takes a long time to merge to develop. On the other hand, we can also create tickets that are too short in scope, and we may end up waiting for each other to approve the merge request, unable to make progress.

Ideally, we should create a ticket that we can close in a couple of days. So, for this particular ticket, if your goal was to 

The comment you made is exactly what we need to discuss together during merge request review. For simple merge requests, you can just tag me in the merge request, I will be able to approve it very quickly. For more complex merge requests, we can address them during our weekly 1:1.

**Comment by taehunk333** [comment]
In this case, you changed a bunch of excel files and just one line in the MATLAB code. So, this can be considered as a trivial request, and you can simply tag me on the merge request, and I can immediately approve it, as soon as I get an email from GitHub notifying me.

**Pull request merged**
